#!/bin/bash

clear

# check for number of arguments
if [ "$#" == "0" ]; then
	echo "ERROR: One argument required"
	exit 1
fi

if [ "$#" -ge "2" ]; then
	echo "ERROR: Provide proper number of arguments"
	exit 1
fi

# store the name of store in a variable
store_name=$1

echo "Enter mysql user name:"
read user
echo "Enter mysql password:"
read password

mysqldump -u $user -p$password $store_name"_development" > $store_name"_development.out"

scp $store_name"_development.out" facoteam1@50.57.231.142:/home/facoteam1/backup/

echo "---------------------------------------------"
echo " Now on server do:"
echo " cd bash "
echo " ./deploy {store_name} "
echo "---------------------------------------------"

ssh facoteam1@50.57.231.142

cap deploy:setup
cap deploy
cap deploy:migrate

echo "---------------------------------------------"
echo " Now on server do:"
echo " cd bash "
echo " ./ssl_implementation {store_name} "
echo "---------------------------------------------"

ssh facoteam1@50.57.231.142

